<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="KPs-MacBook-Air.local" name="com.mobile.hybrid.SampleTest" tests="2" failures="1" timestamp="23 Jan 2019 15:53:42 GMT" time="12.412" errors="0">
  <testcase name="testApp" time="0.050" classname="com.mobile.hybrid.SampleTest">
    <skipped/>
  </testcase> <!-- testApp -->
  <testcase name="testApp" time="12.362" classname="com.mobile.hybrid.SampleTest">
    <failure type="java.lang.AssertionError" message="Locator not found categoryLabel_xpath1">
      <![CDATA[java.lang.AssertionError: Locator not found categoryLabel_xpath1
at org.testng.Assert.fail(Assert.java:96)
at com.qtpselenium.mobile.hybrid.driver.GenericKeywords.reportFailure(GenericKeywords.java:135)
at com.qtpselenium.mobile.hybrid.driver.GenericKeywords.getElement(GenericKeywords.java:101)
at com.qtpselenium.mobile.hybrid.driver.GenericKeywords.click(GenericKeywords.java:82)
at com.qtpselenium.mobile.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:45)
at com.mobile.hybrid.SampleTest.testApp(SampleTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testApp -->
</testsuite> <!-- com.mobile.hybrid.SampleTest -->
